            create table entitlement (
              entitlement_id bigint not null,
              user_id bigint not null,
              item_id varchar(64) default null,
              grant_date timestamp not null,
              expiration_date timestamp default null,
              created_date timestamp not null,
              status smallint not null,
              created_by varchar(32) default null,
              modified_by varchar(32) default null,
              modified_date timestamp not null,
              status_reason varchar(32) default null,
              tag varchar(64) not null,
              use_count bigint not null,
              entitlement_group varchar(64) default null,
              type smallint default 1,
              consumable boolean default null,
              managed_lifecycle boolean default null,
              primary key (entitlement_id)
            );
            create table entitlement_history (
              entitlement_history_id bigint not null,
              action varchar(32) not null,
              entitlement_id bigint not null,
              user_id bigint not null,
              item_id varchar(64) default null,
              grant_date timestamp not null,
              expiration_date timestamp default null,
              created_date timestamp not null,
              status smallint not null,
              created_by varchar(32) default null,
              modified_by varchar(32) default null,
              modified_date timestamp not null,
              status_reason varchar(32) default null,
              tag varchar(64) not null,
              use_count bigint not null,
              entitlement_group varchar(64) not null default 1,
              type smallint default 1,
              consumable boolean default null,
              managed_lifecycle boolean default null,
              primary key (entitlement_history_id)
            );