#!/bin/bash
DIR="$( cd "$( dirname "$0" )" && pwd )"
source ${DIR}/util/common.sh

#master
ssh $DEVOPS_ACCOUNT@$MASTER_HOST << ENDSSH
sudo rm -rf $DEPLOYMENT_PATH
mkdir $DEPLOYMENT_PATH
ENDSSH

scp -r ./ $DEVOPS_ACCOUNT@$MASTER_HOST:$DEPLOYMENT_PATH

ssh $DEVOPS_ACCOUNT@$MASTER_HOST << ENDSSH
sudo chown $DEPLOYMENT_ACCOUNT:$DEPLOYMENT_ACCOUNT $DEPLOYMENT_PATH/*
ENDSSH

#slave
ssh $DEVOPS_ACCOUNT@$SLAVE_HOST << ENDSSH
sudo rm -rf $DEPLOYMENT_PATH
mkdir $DEPLOYMENT_PATH
ENDSSH

scp -r ./ $DEVOPS_ACCOUNT@$SLAVE_HOST:$DEPLOYMENT_PATH

ssh $DEVOPS_ACCOUNT@$SLAVE_HOST << ENDSSH
sudo chown $DEPLOYMENT_ACCOUNT:$DEPLOYMENT_ACCOUNT $DEPLOYMENT_PATH/*
ENDSSH

#replica
ssh $DEVOPS_ACCOUNT@$REPLICA_HOST << ENDSSH
sudo rm -rf $DEPLOYMENT_PATH
mkdir $DEPLOYMENT_PATH
ENDSSH

scp -r ./ $DEVOPS_ACCOUNT@$REPLICA_HOST:$DEPLOYMENT_PATH

ssh $DEVOPS_ACCOUNT@$REPLICA_HOST << ENDSSH
sudo chown $DEPLOYMENT_ACCOUNT:$DEPLOYMENT_ACCOUNT $DEPLOYMENT_PATH/*
ENDSSH