#!/bin/bash
source common.sh

#master
ssh $MASTER_ADDRESS << ENDSSH
rm -rf $DEPLOYMENT_PATH
mkdir $DEPLOYMENT_PATH
ENDSSH

scp -r ./ $MASTER_DEPLOYMENT_PATH

#slave
ssh $SLAVE_ADDRESS << ENDSSH
rm -rf $DEPLOYMENT_PATH
mkdir $DEPLOYMENT_PATH
ENDSSH

scp -r ./ $SLAVE_DEPLOYMENT_PATH