package com.junbo.gradle.bootstrap

import org.gradle.api.DefaultTask
import org.gradle.api.tasks.TaskAction

/**
 * Created by kgu on 5/31/14.
 */
class WriteGitPropertiesTask extends DefaultTask {

    @TaskAction
    void writeGitProperties() {
        def extension = project.rootProject.extensions.getByType(GitPropertiesExtension)
        def properties = extension.gitProperties

        if (properties != null) {
            def generatedRes = new File("$project.buildDir/generated-res")
            generatedRes.mkdirs()

            properties.store(new FileWriter(new File(generatedRes, 'git.properties')),
                    'generated by git-properties plugin')
        }
    }
}
